### ISSUE TITLE
Schema response body generation doesn't work with Lists and Generics

### ISSUE THREAD

**Issue by DibranMulder** [aliencube/AzureFunctions.Extensions#40]
The response bodies for Generic T's are not handled correctly. When you have for instance a `PagedViewModel<MessageViewModel>` class then the schema will not be generated into the OpenApi definitions.

Take for example this functions definition
```csharp
[FunctionName("Get_Messages")]
[OpenApiOperation("get_paged_messages", "messages")]
[OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(PagedViewModel<MessageViewModel>))]
public static async Task<HttpResponseMessage> GetMessages(
[HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "messages")] HttpRequestMessage req)
{
...
}
```

The generated OpenAPI definition is this:
```json
"/messages": {
    "get": {
        "tags": [
            "messages"
        ],
        "operationId": "get_paged_messages",
        "responses": {
            "200": {
                "description": "Payload of PagedViewModel`1",
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/PagedViewModel`1"
                        }
                    }
                }
            }
        }
    }
},

"components": {
    "securitySchemes": {
        "authKey": {
            "type": "apiKey",
            "name": "x-functions-key",
            "in": "header"
        }
    }
}
```
The schemas property in the components is missing. Same goes for using List<T> or IENumerable<T>. Seems only to work for flat objects.

**Comment by DibranMulder** [comment]
I think the bug is in `GetOpenApiSchemas`, it filters out Array's. But what if my type is only used in lists? Then it isn't part of the schema. In my opinion these things have to be fixed:

1. Use the `IsOpenApiArray` check to determine if the type is an array.
2. If its an Array then the ElementType or the Generic SubType has to be selected. Just like in the `ToOpenApiSchema` method. (`type.GetElementType() ?? type.GetGenericArguments()[0]`)

```csharp
public Dictionary<string, OpenApiSchema> GetOpenApiSchemas(List<MethodInfo> elements)
{
    var requests = elements.SelectMany(p => p.GetCustomAttributes<OpenApiRequestBodyAttribute>(inherit: false))
                            .Select(p => p.BodyType);
    var responses = elements.SelectMany(p => p.GetCustomAttributes<OpenApiResponseBodyAttribute>(inherit: false))
                            .Select(p => p.BodyType);
    var types = requests.Union(responses)
                        .Distinct()
                        .Where(p => p != typeof(JObject))
                        .Where(p => p != typeof(JToken))
                        .Where(p => !typeof(Array).IsAssignableFrom(p))
                        .Where(p => !p.IsGenericType)
                        ;
    var schemas = types.ToDictionary(p => p.Name, p => p.ToOpenApiSchema());

    return schemas;
}
```

**Comment by glennular** [comment]
I ran into the same issue when typing to adopt the new release.

Fixed in #42

**Comment by justinyoo** [comment]
@DibranMulder Can you show me the class definition of `PagedViewModel<T>` and `MessageViewModel`?

**Comment by justinyoo** [comment]
Apparently @glennular 's PR #42 has sorted out the issue at a certain level, but I'm not sure whether it's solved your issue or not.

**Comment by DibranMulder** [comment]
> Apparently @glennular 's PR #42 has sorted out the issue at a certain level, but I'm not sure whether it's solved your issue or not.

```csharp
public class PagedViewModel<T>
{
    public int PageIndex { get; set; }
    public int TotalResults { get; set; }
    public IEnumerable<T> Results { get; set; }
}

public class MessageViewModel
{
    public int Id { get; set; }
    public short Severity { get; set; }
    public string Type { get; set; }
    public string Message { get; set; }
    public string ProductId { get; set; }
    public DateTime TimeStamp { get; set; }
    public bool Read { get; set; }
}
```
And also for lists it doesn't work. So any List<T> doesn't add a schema definition.
```csharp
[OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(List<T>))]
```
However when `T` is added as root response body then it works again.
```csharp
[OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(T))]
```
I think this is because all generic types are filtered out.

**Comment by justinyoo** [comment]
> And also for lists it doesn't work. So any List doesn't add a schema definition.
> 
> ```cs
> [OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(List<T>))]
> ```
> 
> However when `T` is added as root response body then it works again.
> 
> ```cs
> [OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(T))]
> ```

This has been fixed in 1.5.3. Can you double check at your end?

**Comment by DibranMulder** [comment]
Can confirm that Lists work.
![image](https://user-images.githubusercontent.com/5592416/59347050-fcff5e00-8d13-11e9-830a-05d7fa40c158.png)

However Generic<T> is still broken.
![image](https://user-images.githubusercontent.com/5592416/59346974-d04b4680-8d13-11e9-8acc-0f8208802267.png)
![image](https://user-images.githubusercontent.com/5592416/59346997-db05db80-8d13-11e9-89d8-359e150cd969.png)

**Comment by justinyoo** [comment]
@DibranMulder Yes, the generic still needs more work. Thanks for confirming the `List<T>` bit!

**Comment by justinyoo** [comment]
@DibranMulder The generics has been fixed and released to [NuGet](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/1.5.4). Thanks for your patience!

**Comment by Dan-Williams93** [comment]
Hi @justinyoo, it looks like the response type with generics described by @DibranMulder is still an issue in the latest release. I am currently trying to make use of the OpenApiResponseBody attribute in the same way, using the example as below


```
    public class GenericModel<T>
    {
        public IEnumerable<T> Results { get; set; }
    }

    public class MyExampleType
    {
        public string SomeValue { get; set; }
    }

    [OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(GenericModel<MyExampleType>))]

```


However, when looking at the definition, the generic model is shown as the response type but it fails to show the internal generic enumerable as it is not defined in the schema definition.

![image](https://user-images.githubusercontent.com/9553047/87438428-6cb2dd00-c5e7-11ea-963a-ee8fe61cc208.png)

![image](https://user-images.githubusercontent.com/9553047/87438512-881de800-c5e7-11ea-88da-4f0c5c3e25bc.png)
